target("test_Yutrel_cli_options")
    set_kind("binary")
    set_default(false)
    set_group("tests/Yutrel/app")
    set_rundir("$(projectdir)")

    add_files("test_cli_options.cpp", "../../src/app/cli_options.cpp")
    add_includedirs("../../src/app", "$(projectdir)/ext/LuisaCompute/src/tests")
    add_deps("lc-core")
target_end()

target("test_Yutrel_scene_loader")
    set_kind("binary")
    set_default(false)
    set_group("tests/Yutrel/app")
    set_rundir("$(projectdir)")

    add_files("test_scene_loader.cpp", "../../src/app/scene_loader.cpp")
    add_includedirs("../../src/app", "$(projectdir)/ext/LuisaCompute/src/tests")
    add_deps("YutrelPbrt")
target_end()
